version: '2'

services:
  ckan-hobbit-db:
    image: postgres:9.6.0
    container_name: ckan-hobbit-db
    environment:
      - POSTGRES_PASSWORD=ckan
      - POSTGRES_USER=ckan
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=ckan
    networks:
      - ckan-hobbit
    restart: always
  ckan-hobbit-solr:
    image: earthquakesan/ckan-solr:2.6.0
    container_name: ckan-hobbit-solr
    networks:
      - ckan-hobbit
    restart: always
  hobbit-ckan:
    image: earthquakesan/ckan:2.6.0-hobbit
    container_name: hobbit-ckan
    depends_on:
      - ckan-hobbit-db
      - ckan-hobbit-solr
    environment:
      - DATABASE_URL=postgresql://ckan:ckan@ckan-hobbit-db:5432/ckan
      - SOLR_URL=http://ckan-hobbit-solr:8983/solr/ckan
      - RECAPTCHA_PUBLIC_KEY=publickey 
      - RECAPTCHA_PRIVATE_KEY=privatekey
      - SITE_URL=http://localhost
      - VIRTUAL_HOST=localhost
    networks:
      - ckan-hobbit
    restart: always

networks:
  ckan-hobbit:
