version: '2'

services:
  ckan-db:
    image: postgres:9.6.0
    container_name: ckan-db
    environment:
      - POSTGRES_PASSWORD=ckan
      - POSTGRES_USER=ckan
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=ckan
    volumes:
      - /tmp/ckan-hobbit-db:/var/lib/postgresql/data
    restart: always
    networks:
      - ckan-net

  ckan-solr:
    image: earthquakesan/ckan-solr:2.6.0
    container_name: ckan-solr
    restart: always
    networks:
      - ckan-net

  ckan:
    image: earthquakesan/ckan:2.6.0
    container_name: ckan-web
    restart: always
    depends_on:
      - ckan-db
      - ckan-solr
    environment:
      - DATABASE_URL=postgresql://ckan:ckan@ckan-db:5432/ckan
      - SOLR_URL=http://ckan-solr:8983/solr/ckan
      - RECAPTCHA_PUBLIC_KEY=CHANGE_ME
      - RECAPTCHA_PRIVATE_KEY=CHANGE_ME
      - SITE_URL=http://ckan.vhost.tld
      - VIRTUAL_HOST=ckan.vhost.tld
    #volumes:
      #- /tmp/ckan-uploads:/var/lib/ckan
    networks:
      - ckan-net

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - ckan-net
    volumes:
      - /tmp/docker/nginx/certs:/etc/nginx/certs:ro
      - /tmp/docker/nginx/vhost:/etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /tmp/docker/nginx/htpasswd:/etc/nginx/htpasswd:ro

networks:
  ckan-net:
    external:
      name: ckan-net
