version: '2'

services:
  ckan-db:
    image: postgres:9.6.0
    container_name: ckan-db
    environment:
      - POSTGRES_PASSWORD=ckan
      - POSTGRES_USER=ckan
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=ckan
    volumes:
      - volume-ckan-db:/var/lib/postgresql/data
    restart: always
    networks:
      - ckan-net

  ckan-solr:
    image: earthquakesan/ckan-solr:2.6.0
    container_name: ckan-solr
    restart: always
    volumes:
      - volume-ckan-solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - ckan
      - /ckan-configset
    networks:
      - ckan-net

  ckan-web:
    image: earthquakesan/ckan:2.6.0
    container_name: ckan-web
    restart: always
    depends_on:
      - ckan-db
      - ckan-solr
    ports:
      - 13337:80
    environment:
      - DATABASE_URL=postgresql://ckan:ckan@ckan-db:5432/ckan
      - SOLR_URL=http://ckan-solr:8983/solr/ckan
      - RECAPTCHA_PUBLIC_KEY=
      - RECAPTCHA_PRIVATE_KEY=
      - SITE_URL=http://ckan.example.org
    volumes:
      - volume-ckan-web-uploads:/var/lib/ckan
    networks:
      - ckan-net

volumes:
  volume-ckan-db:
    external:
      name: volume-ckan-db
  volume-ckan-solr:
    external:
      name: volume-ckan-solr
  volume-ckan-web-uploads:
    external:
      name: volume-ckan-web-uploads

networks:
  ckan-net:
    external:
      name: ckan-net
