version: '2'

services:
  ckan-hobbit-db:
    image: postgres:9.6.0
    container_name: ckan-hobbit-db
    environment:
      - POSTGRES_PASSWORD=ckan
      - POSTGRES_USER=ckan
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=ckan
    volumes:
      - /data/docker/ckan-hobbit-db:/var/lib/postgresql/data
    restart: always
  ckan-hobbit-solr:
    image: earthquakesan/ckan-solr:2.8.0
    container_name: ckan-hobbit-solr
    restart: always
    ports:
      - 8983:8983
  ckan-hobbit-redis:
    image: redis:3.2.12
  hobbit-ckan:
    image: earthquakesan/ckan:2.8.0
    container_name: hobbit-ckan
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:ckan@ckan-hobbit-db:5432/ckan
      - CKAN_SOLR_URL=http://ckan-hobbit-solr:8983/solr/ckan
      - CKAN_RECAPTCHA_PUBLICKEY=
      - CKAN_RECAPTCHA_PRIVATEKEY=
      - CKAN_SITE_URL=http://localhost
      - CKAN_REDIS_URL=redis://ckan-hobbit-redis:6379/0
      - CKAN_DATAPUSHER_URL=http://127.0.0.1:8800/
    volumes:
      - /data/docker/ckan-uploads:/var/lib/ckan
    restart: always
    ports:
      - 80:5000
