version: '2'

services:
  ckan-hobbit-db:
    image: postgres:9.6.0
    container_name: ckan-hobbit-db
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=
    volumes:
      - /data/docker/ckan-hobbit-db:/var/lib/postgresql/data
    restart: always
    network_mode: "bridge"
    restart: always
  ckan-hobbit-solr:
    image: earthquakesan/ckan-solr:2.6.0
    container_name: ckan-hobbit-solr
    restart: always
    network_mode: "bridge"
  hobbit-ckan:
    image: earthquakesan/ckan:2.6.0-hobbit
    container_name: hobbit-ckan
    depends_on:
      - ckan-hobbit-db
      - ckan-hobbit-solr
    environment:
      - DATABASE_URL=postgresql://ckan:ckan@ckan-hobbit-db:5432/ckan
      - SOLR_URL=http://ckan-hobbit-solr:8983/solr/ckan
      - RECAPTCHA_PUBLIC_KEY=
      - RECAPTCHA_PRIVATE_KEY=
      - SITE_URL=https://ckan.project-hobbit.eu
      - VIRTUAL_HOST=ckan.project-hobbit.eu
      - LETSENCRYPT_HOST=ckan.project-hobbit.eu
      - LETSENCRYPT_EMAIL=
    volumes:
      - /data/docker/ckan-uploads:/var/lib/ckan
    restart: always
    network_mode: "bridge"
    links:
      - "ckan-hobbit-solr:ckan-hobbit-solr"
      - "ckan-hobbit-db:ckan-hobbit-db"
